#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap "rm -f .git/tags.$$" EXIT
git ls-files | \
    ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-sql
mv .git/tags.$$ .git/tags
